return {
  {
    "pwntester/octo.nvim",
    dependencies = {
      "nvim-lua/plenary.nvim",
      "nvim-telescope/telescope.nvim",
      "nvim-tree/nvim-web-devicons",
    },
    cmd = "Octo",
    keys = {
      { "<leader>op",  "<cmd>Octo pr list<cr>",      desc = "Octo: list PRs" },
      { "<leader>ovr", "<cmd>Octo review resume<cr>", desc = "resume review" },
      { "<leader>ovR", "<cmd>Octo review start<cr>",  desc = "start new review" },
    },
    config = function()
      local ok, wk = pcall(require, "which-key")
      if ok then
        wk.add({
          { "<leader>o",  group = "octo" },
          { "<leader>oa", group = "assign" },
          { "<leader>oc", group = "comment" },
          { "<leader>oi", group = "issue" },
          { "<leader>ol", group = "label" },
          { "<leader>op", group = "pr" },
          { "<leader>or", group = "react" },
          { "<leader>ov", group = "review" },
        })
      end

      vim.treesitter.language.register("markdown", "octo")

      vim.api.nvim_create_autocmd("FileType", {
        pattern = "octo",
        callback = function()
          vim.wo.conceallevel = 2
        end,
      })

      require("octo").setup({
        use_local_fs = false,
        enable_builtin = true,
        default_remote = { "upstream", "origin" },
        ssh_aliases = {},
        picker = "telescope",
        picker_config = {
          use_emojis = false,
        },
        comment_icon = "▎",
        outdated_icon = "󰅒 ",
        resolved_icon = " ",
        reaction_viewer_hint_icon = " ",
        user_icon = " ",
        timeline_marker = " ",
        timeline_indent = 2,
        right_bubble_delimiter = "",
        left_bubble_delimiter = "",
        github_hostname = "",
        snippet_context_lines = 4,
        gh_env = {},
        timeout = 5000,
        ui = {
          use_signcolumn = true,
        },
        issues = {
          order_by = { field = "CREATED_AT", direction = "DESC" },
        },
        pull_requests = {
          order_by = { field = "CREATED_AT", direction = "DESC" },
          always_select_remote_on_create = false,
        },
        file_panel = {
          size = 10,
        },
        mappings = {
          issue = {
            close_issue             = { lhs = "<leader>oic", desc = "close issue" },
            reopen_issue            = { lhs = "<leader>oio", desc = "reopen issue" },
            list_issues             = { lhs = "<leader>oil", desc = "list issues" },
            reload                  = { lhs = "<leader>oR",  desc = "reload" },
            open_in_browser         = { lhs = "<leader>ob",  desc = "open in browser" },
            copy_url                = { lhs = "<leader>oy",  desc = "copy url" },
            add_assignee            = { lhs = "<leader>oaa", desc = "add assignee" },
            remove_assignee         = { lhs = "<leader>oad", desc = "remove assignee" },
            create_label            = { lhs = "<leader>olc", desc = "create label" },
            add_label               = { lhs = "<leader>ola", desc = "add label" },
            remove_label            = { lhs = "<leader>old", desc = "remove label" },
            goto_issue              = { lhs = "<leader>ogi", desc = "go to issue" },
            add_comment             = { lhs = "<leader>oca", desc = "add comment" },
            add_reply               = { lhs = "<leader>ocr", desc = "add reply" },
            delete_comment          = { lhs = "<leader>ocd", desc = "delete comment" },
            next_comment            = { lhs = "]c",          desc = "next comment" },
            prev_comment            = { lhs = "[c",          desc = "prev comment" },
            react_hooray            = { lhs = "<leader>orp", desc = "react 🎉" },
            react_heart             = { lhs = "<leader>orh", desc = "react ❤️" },
            react_eyes              = { lhs = "<leader>ore", desc = "react 👀" },
            react_thumbs_up         = { lhs = "<leader>or+", desc = "react 👍" },
            react_thumbs_down       = { lhs = "<leader>or-", desc = "react 👎" },
            react_rocket            = { lhs = "<leader>orr", desc = "react 🚀" },
            react_laugh             = { lhs = "<leader>orl", desc = "react 😄" },
            react_confused          = { lhs = "<leader>orc", desc = "react 😕" },
          },
          pull_request = {
            checkout_pr             = { lhs = "<leader>opo", desc = "checkout PR" },
            merge_pr                = { lhs = "<leader>opm", desc = "merge PR" },
            squash_and_merge_pr     = { lhs = "<leader>opsm", desc = "squash and merge" },
            rebase_and_merge_pr     = { lhs = "<leader>oprm", desc = "rebase and merge" },
            list_commits            = { lhs = "<leader>opc", desc = "list commits" },
            list_changed_files      = { lhs = "<leader>opf", desc = "list changed files" },
            show_pr_diff            = { lhs = "<leader>opd", desc = "show diff" },
            add_reviewer            = { lhs = "<leader>ova", desc = "add reviewer" },
            remove_reviewer         = { lhs = "<leader>ovd", desc = "remove reviewer" },
            close_issue             = { lhs = "<leader>oic", desc = "close PR" },
            reopen_issue            = { lhs = "<leader>oio", desc = "reopen PR" },
            reload                  = { lhs = "<leader>oR",  desc = "reload" },
            open_in_browser         = { lhs = "<leader>ob",  desc = "open in browser" },
            copy_url                = { lhs = "<leader>oy",  desc = "copy url" },
            add_assignee            = { lhs = "<leader>oaa", desc = "add assignee" },
            remove_assignee         = { lhs = "<leader>oad", desc = "remove assignee" },
            add_label               = { lhs = "<leader>ola", desc = "add label" },
            remove_label            = { lhs = "<leader>old", desc = "remove label" },
            add_comment             = { lhs = "<leader>oca", desc = "add comment" },
            delete_comment          = { lhs = "<leader>ocd", desc = "delete comment" },
            next_comment            = { lhs = "]c",          desc = "next comment" },
            prev_comment            = { lhs = "[c",          desc = "prev comment" },
            react_hooray            = { lhs = "<leader>orp", desc = "react 🎉" },
            react_heart             = { lhs = "<leader>orh", desc = "react ❤️" },
            react_eyes              = { lhs = "<leader>ore", desc = "react 👀" },
            react_thumbs_up         = { lhs = "<leader>or+", desc = "react 👍" },
            react_thumbs_down       = { lhs = "<leader>or-", desc = "react 👎" },
            react_rocket            = { lhs = "<leader>orr", desc = "react 🚀" },
            react_laugh             = { lhs = "<leader>orl", desc = "react 😄" },
            react_confused          = { lhs = "<leader>orc", desc = "react 😕" },
          },
          review_diff = {
            submit_review           = { lhs = "<leader>ovs", desc = "submit review" },
            discard_review          = { lhs = "<leader>ovd", desc = "discard review" },
            add_review_comment      = { lhs = "<leader>oca", desc = "add review comment", mode = { "n", "x" } },
            add_review_suggestion   = { lhs = "<leader>osa", desc = "add suggestion", mode = { "n", "x" } },
            focus_files             = { lhs = "<leader>oe",  desc = "focus file panel" },
            toggle_files            = { lhs = "<leader>ot",  desc = "toggle file panel" },
            next_thread             = { lhs = "]t",          desc = "next thread" },
            prev_thread             = { lhs = "[t",          desc = "prev thread" },
            select_next_entry       = { lhs = "]q",          desc = "next changed file" },
            select_prev_entry       = { lhs = "[q",          desc = "prev changed file" },
            select_first_entry      = { lhs = "[Q",          desc = "first changed file" },
            select_last_entry       = { lhs = "]Q",          desc = "last changed file" },
            close_review_tab        = { lhs = "<leader>ox",  desc = "close review tab" },
            toggle_viewed           = { lhs = "<leader>ov",  desc = "toggle viewed" },
            goto_file               = { lhs = "gf",          desc = "go to file" },
            review_commits          = { lhs = "<leader>oC",  desc = "review commits" },
          },
          review_thread = {
            add_comment             = { lhs = "<leader>oca", desc = "add comment" },
            add_suggestion          = { lhs = "<leader>osa", desc = "add suggestion" },
            delete_comment          = { lhs = "<leader>ocd", desc = "delete comment" },
            resolve_thread          = { lhs = "<leader>ort", desc = "resolve thread" },
            unresolve_thread        = { lhs = "<leader>orT", desc = "unresolve thread" },
            next_comment            = { lhs = "]c",          desc = "next comment" },
            prev_comment            = { lhs = "[c",          desc = "prev comment" },
            select_next_entry       = { lhs = "]q",          desc = "next changed file" },
            select_prev_entry       = { lhs = "[q",          desc = "prev changed file" },
            select_first_entry      = { lhs = "[Q",          desc = "first changed file" },
            select_last_entry       = { lhs = "]Q",          desc = "last changed file" },
            close_review_tab        = { lhs = "<leader>ox",  desc = "close review tab" },
          },
          submit_win = {
            approve_review          = { lhs = "<leader>oa",  desc = "approve", mode = { "n" } },
            comment_review          = { lhs = "<leader>om",  desc = "comment only", mode = { "n" } },
            request_changes         = { lhs = "<leader>or",  desc = "request changes", mode = { "n" } },
            close_review_tab        = { lhs = "<leader>ox",  desc = "close", mode = { "n" } },
          },
          file_panel = {
            submit_review           = { lhs = "<leader>ovs", desc = "submit review" },
            discard_review          = { lhs = "<leader>ovd", desc = "discard review" },
            next_entry              = { lhs = "j",           desc = "next file" },
            prev_entry              = { lhs = "k",           desc = "prev file" },
            select_entry            = { lhs = "<cr>",        desc = "open file diff" },
            refresh_files           = { lhs = "R",           desc = "refresh" },
            focus_files             = { lhs = "<leader>oe",  desc = "focus file panel" },
            toggle_files            = { lhs = "<leader>ot",  desc = "toggle file panel" },
            select_next_entry       = { lhs = "]q",          desc = "next changed file" },
            select_prev_entry       = { lhs = "[q",          desc = "prev changed file" },
            select_first_entry      = { lhs = "[Q",          desc = "first changed file" },
            select_last_entry       = { lhs = "]Q",          desc = "last changed file" },
            close_review_tab        = { lhs = "<leader>ox",  desc = "close review tab" },
            toggle_viewed           = { lhs = "<leader>ov",  desc = "toggle viewed" },
            goto_file               = { lhs = "gf",          desc = "go to file" },
            review_commits          = { lhs = "<leader>oC",  desc = "review commits" },
          },
        },
      })
    end,
  },
}
